version: '3.3'

services:
  api:
    build:
      context: ../src/backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000']
    networks:
      - app_network

  react-app:
    build:
      context: ../src/client/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: ['npm', 'start']
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
