name: Deploy static content to Pages

on:
  push:
    branches: ["mainApp"]  # Указываем ветку, для которой срабатывает workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout mainApp branch
        run: git checkout mainApp  # Переключаемся на ветку mainApp

      - name: Set up Docker
        uses: production/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          docker-compose -f production/docker-compose.yml up -d --build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
